# Generated by Django 4.1.4 on 2022-12-23 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xlease', '0005_alter_item_lease_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='xlease.country'),
        ),
    ]
