# Generated by Django 4.1.4 on 2022-12-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xlease', '0007_alter_customer_city_alter_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
