# Generated by Django 4.1.4 on 2022-12-24 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xlease', '0008_customer_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(blank=True, default='AfricanPear.jpeg', upload_to='xlease/customer/image'),
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='xlease/items/images')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='xlease.item')),
            ],
        ),
    ]
