# Generated by Django 4.1.4 on 2022-12-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xlease', '0010_rename_item_id_itemimage_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(upload_to='xlease/items'),
        ),
    ]
