# Generated by Django 4.1.4 on 2022-12-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xlease', '0011_alter_itemimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(default='AfricanPear.jpeg', upload_to='xlease/customer/images'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(upload_to='xlease/item/images'),
        ),
    ]
